### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by RakibRyan** [NyokoDev/Lumina#14]
Hi I was wondering if you would add a license like MIT or GNU to it. I'd like to make changes and also publish to nexus mods for people like me who own the game on epic games or gog.

**Comment by NyokoDev** [comment]
Latest Lumina release is available on GitHub releases and on SkyLinx Mod Resource for Epic Games users.

**Comment by RakibRyan** [comment]
would be glad if you could upload to nexus mods. As many people including me use nexus mod's vortex mod manager as a central mod manager. I already use a lot of launcers for many games would like to avoid downloading another one if possible.
